<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$route['default_controller'] = 'home';
$route['404_override'] = 'home/error';
$route['search'] = 'home/search';
$route["gallery"]="gallery/photo_gallery";
$route["video-gallery"]="gallery/video_gallery";
$route["(:any).htm"]="home/error";
$route["infrastructure"]="about/infrastructure";
$route['blogs'] = 'blog/view';
$route['blog/(:any)'] = 'blog/read/$1';
$route["about"]="about/about";
$route["why-choose-us"]="about/choose";
$route["testimonials"]="about/testimonials";
$route["privacy-policy"]="about/privacy";
$route["terms-and-condition"]="about/condition";
$route["car-shifting"]="services/carshifting";
$route["courier-service"]="services/courier";
$route["home-shifting"]="services/homeshifting";
$route["iba-approved"]="services/ibaapproved";
$route["insurance-service"]="services/insurances";
$route["loading-unloading-service"]="services/loading";
$route["luggage-delivery"]="services/luggage";
$route["office-shifting"]="services/office";
$route["packing-unpacking-service"]="services/packing";
$route["branches"]="packers_movers/state";
$route["contacts"]="contacts/contacts";
$route["packers-movers-(:any)-india"]="packers_movers/state_services/$1";
$route["(:any)-packers-movers-(:any)"]="packers_movers/city/$2/$1";
$route["bihar"]="packers_movers/state_services/bihar";
$route["maharashtra"]="packers_movers/state_services/maharashtra";
$route["delhi"]="packers_movers/state_services/delhi";
$route["uttarpradesh"]="packers_movers/state_services/uttarpradesh";
$route["punjab"]="packers_movers/state_services/punjab";

$route['translate_uri_dashes'] = TRUE;